apiVersion: v1
kind: Service
metadata:
  name: asset-service
  namespace: asset-service
  labels:
    app.kubernetes.io/name: asset-service
    app.kubernetes.io/part-of: asset-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: asset-service
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
